# Generated by Django 5.2.5 on 2025-08-31 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_guestuser_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.guestuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
