# Generated by Django 5.2.5 on 2025-08-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_price',
            field=models.IntegerField(default=0),
        ),
    ]
