# Generated by Django 5.2.5 on 2025-08-31 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_alter_bid_amount_alter_product_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
