# Generated by Django 5.2.5 on 2025-09-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_product_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
