# Generated by Django 5.2.5 on 2025-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='last_bid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='anti_sniping_active',
            field=models.BooleanField(default=False),
        ),
    ]
