# Generated by Django 5.2.5 on 2025-11-09 03:25

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_guestuser_last_bid_time_product_anti_sniping_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['product', '-created_at'], name='product_bids_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['start_time', 'end_time', 'is_active'], name='active_auctions_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-end_time'], name='finished_auctions_idx'),
        ),
    ]
