# Generated by Django 5.2.5 on 2025-11-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_alter_bid_options_alter_bid_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_silent_auction',
            field=models.BooleanField(default=False, help_text='En subastas silenciosas, los usuarios no ven las pujas de otros hasta que termine', verbose_name='Subasta Silenciosa'),
        ),
    ]
