# Generated by Django 5.2.5 on 2025-11-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_product_is_silent_auction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount', 'created_at']},
        ),
    ]
